name: Text Deno 1.26～1.28

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version:
          - v1.26.x # Release 2022.09.28
          - v1.27.x # Release 2022.10.27
          - v1.28.x # Release 2022.11.13

    steps:
      - uses: actions/checkout@v3
      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Run deno test
        run: |
          deno task testcheck